name: script-runner-ci

on:
  push:
    branches:
      - main
jobs:
  script-runner:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: make script executable
        run: chmod +x bash_github_actions.sh
    
      - name: running bash script
        run: ./bash_github_actions.sh
      
